services:
  postgres-db:
    image: postgres:15
    container_name: jpa_practice_db
    environment:
      POSTGRES_USER: admin_jpa
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: project_db
    ports:
      - "5432:5432"
    volumes:
      - jpa_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  java21:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: jpa_practice_java21
    working_dir: /workspace
    user: "${UID}:${GID}"
    volumes:
      - ./:/workspace
    depends_on:
      - postgres-db
    environment:
      HOME: /workspace/.container_home
      JDBC_URL: jdbc:postgresql://postgres-db:5432/project_db
      JDBC_USER: admin_jpa
      JDBC_PASSWORD: super_secret_password
    tty: true
    stdin_open: true
    command: sleep infinity

volumes:
  jpa_db_data:
